<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductionDataSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('blog_categories')->truncate();
        DB::table('posts')->truncate();
        DB::table('projects')->truncate();
        DB::table('site_settings')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $u = 'https://images.unsplash.com/photo-';
        $q = '?fm=jpg&q=60&w=800&auto=format&fit=crop';

        // ── Blog categories ───────────────────────────────────────────────
        DB::table('blog_categories')->insert([
            ['id'=>1,'name'=>'Corporate', 'slug'=>'corporate', 'sort_order'=>1,'created_at'=>'2026-05-27 02:56:23','updated_at'=>'2026-05-27 02:56:23'],
            ['id'=>2,'name'=>'Lifestyle', 'slug'=>'lifestyle', 'sort_order'=>2,'created_at'=>'2026-05-27 02:56:24','updated_at'=>'2026-05-27 02:56:24'],
            ['id'=>3,'name'=>'Insights',  'slug'=>'insights',  'sort_order'=>3,'created_at'=>'2026-05-27 02:56:24','updated_at'=>'2026-05-27 02:56:24'],
        ]);

        // ── Blog posts ────────────────────────────────────────────────────
        DB::table('posts')->insert([
            [
                'id'           => 1,
                'title'        => 'Welcome to My Corner of the Internet',
                'slug'         => 'welcome-to-my-corner-of-the-internet',
                'excerpt'      => 'A personal note from Ruth on why she started this blog, what you can expect, and what My Perfect Stitch really stands for.',
                'body'         => '<p>I have been meaning to write this post for a long time. Not because I did not know what to say — but because I wanted to say it properly.</p><p>This blog is my space. A place where I talk about the things that matter to me: building a business from the ground up, the craft of making things with your hands, what it means to be a Zambian woman carving out space in the design and manufacturing world, and the honest, sometimes uncomfortable lessons that come with entrepreneurship.</p><h2>What You Will Find Here</h2><p>I am not interested in writing a blog that is just marketing. You can find that everywhere. What I want to write — and what I hope you want to read — is something more real.</p><p>I will write about the behind-the-scenes of My Perfect Stitch: the ideas that worked, the ones that did not, the pieces I am most proud of, and the process that goes into every commission. I will write about what it feels like to run a growing enterprise in Zambia — the challenges, the small victories, and the community that makes it all possible.</p><h2>Who This Is For</h2><p>If you are a customer of My Perfect Stitch — welcome. I hope this gives you a deeper sense of the people and ideas behind the things you have bought or are thinking of buying.</p><p>If you are an entrepreneur, especially a young African woman thinking about making the leap — this is very much for you. I was you not long ago. I still remember what it felt like to want something this much and not yet know how to reach it.</p><p>If you are simply curious about African design, craftsmanship, and what a purpose-driven business actually looks like from the inside — pull up a chair. I think you will find something worth staying for.</p><p>Thank you for being here.</p><p><em>— Ruth</em></p>',
                'cover_image'  => $u.'1590650153855-d9e808231d41'.$q,
                'published'    => 1,
                'published_at' => '2026-05-26 16:49:02',
                'category'     => 'Lifestyle',
                'created_at'   => '2026-05-26 16:49:02',
                'updated_at'   => '2026-05-27 03:02:30',
            ],
            [
                'id'           => 2,
                'title'        => 'Five Things I Wish I Knew Before Starting My Business',
                'slug'         => 'five-things-i-wish-i-knew-before-starting-my-business',
                'excerpt'      => 'The honest lessons Ruth wishes someone had told her before she launched My Perfect Stitch — practical wisdom for first-time entrepreneurs.',
                'body'         => '<p>When I left my government job to start My Perfect Stitch, I was confident. I had a product people wanted. I had savings. I had a plan — or at least, something I was calling a plan.</p><p>What I did not have was the hard-won knowledge that only comes from doing the thing. Here are five lessons I would go back and tell myself if I could.</p><h2>1. Your First Price Is Almost Always Too Low</h2><p>I underpriced my work for the first eighteen months. I was afraid that if I charged what the work was worth, clients would walk away. Most of them would not have. Price your work honestly from the beginning — it is far harder to raise prices later than to set them right from the start.</p><h2>2. Cash Flow Is Not the Same as Profit</h2><p>I had months where the business looked healthy on paper but I was scrambling to pay suppliers. Understanding the difference between revenue, profit, and cash in your account is not optional knowledge for a business owner. Learn it early.</p><h2>3. Your Network Is Your First Market</h2><p>Every significant early client I had came through a personal connection. Not advertising. Not a website. A conversation with someone who already trusted me. Invest in relationships before you need them.</p><h2>4. Saying No Is a Business Strategy</h2><p>In the early days I took almost every commission, even the ones that did not fit what I was trying to build. Each misfit project cost me more than it paid — in time, in energy, and in the direction of the brand. Learning to say no to the wrong work is how you make room for the right work.</p><h2>5. The Business Will Become What You Practice</h2><p>If you practice cutting corners, the business becomes one that cuts corners. If you practice quality — in the work, in the communication, in the relationships — the business becomes known for quality. Every small decision is practice. Choose carefully what you are rehearsing.</p>',
                'cover_image'  => $u.'1720247520862-7e4b14176fa8'.$q,
                'published'    => 1,
                'published_at' => '2026-05-24 16:49:03',
                'category'     => 'Corporate',
                'created_at'   => '2026-05-26 16:49:03',
                'updated_at'   => '2026-05-27 03:02:31',
            ],
            [
                'id'           => 3,
                'title'        => 'A Day in the My Perfect Stitch Studio',
                'slug'         => 'a-day-in-the-my-perfect-stitch-studio',
                'excerpt'      => 'What does a working day actually look like at My Perfect Stitch? Ruth takes you inside the studio — the rhythms, the people, and the work.',
                'body'         => '<p>People often ask me what a typical day looks like at My Perfect Stitch. The honest answer is that there is no such thing as a typical day. But there are rhythms — and I want to share them with you.</p><h2>The Morning</h2><p>I am in the studio early. Before the team arrives, I like to walk through the space quietly — checking on pieces in progress, looking at the order board, thinking about what needs attention that day. It is the only quiet hour in a working studio, and I have learned to treasure it.</p><p>By 8am the team is arriving. We start with a short stand-up: what is in production, what is being delivered this week, what problems need solving. It takes fifteen minutes and it sets the day.</p><h2>The Middle of the Day</h2><p>Most of the actual making happens between 9am and 2pm. Sawing, joinery, upholstery work, sewing, finishing — the studio is loud and busy and it smells of wood and leather and textile dye. I love it.</p><p>I move between my desk and the workshop floor. There are always client emails to answer, quotes to prepare, deliveries to coordinate. But I make a point of spending at least two hours a day doing hands-on work. If I stop making, I stop being able to lead the people who make. That feels important to me.</p><h2>The Afternoon</h2><p>Afternoons are for client meetings, site visits, and the business development work that keeps the pipeline full. I try to batch these so they do not interrupt the morning production flow.</p><p>At around 4pm the studio quiets down. I use the last hour to plan the next day — reviewing what was completed, what is outstanding, what I need to think about overnight.</p><h2>What the Studio Feels Like</h2><p>What I want people to understand about My Perfect Stitch is that it is not just a factory. It is a place where people take pride in what they make. When a piece leaves here, everyone who touched it knows they made something worth making.</p><p>That culture did not happen by accident. It was built, deliberately, one day at a time. And it is, honestly, the thing I am most proud of.</p>',
                'cover_image'  => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'published'    => 1,
                'published_at' => '2026-05-27 03:04:33',
                'category'     => 'Lifestyle',
                'created_at'   => '2026-05-26 16:49:03',
                'updated_at'   => '2026-05-27 03:04:33',
            ],
            [
                'id'           => 4,
                'title'        => 'What If Your Hobby Is the Start of a Million-Dollar Business?',
                'slug'         => 'what-if-your-hobby-is-the-start-of-a-million-dollar-business',
                'excerpt'      => 'Ruth Kayira shares the story behind her TEDx talk and the moment she realised My Perfect Stitch was more than a pastime.',
                'body'         => '<p>When I stood on the TEDx stage in 2022, I had one message: the thing you do on weekends, the skill you have been brushing aside as "just a hobby" — that could be your life\'s work. That could be your business.</p><p>My Perfect Stitch started exactly that way. I was a government official with a stable career, and on weekends I was sewing, designing furniture, crafting bags. Friends and family admired the pieces. A few asked if they could buy them. I said yes — and everything changed from there.</p><h2>The Leap No One Talks About</h2><p>Every entrepreneur story you read online skips the fear part. It skips the moment when you are sitting at your desk, calculating whether you can afford to leave, wondering if anyone will actually pay for what you make.</p><p>I sat with that fear for two years before I acted. And when I finally handed in my resignation and told my family I was going full-time with My Perfect Stitch — the ground did not swallow me. The clients came. The word spread. The business grew.</p><h2>Start Before You Are Ready</h2><p>The most important lesson I share with young entrepreneurs: you will never feel completely ready. The conditions will never be perfect. Start anyway. Start small. Start with what you have, where you are.</p><p>My Perfect Stitch began with a second-hand sewing machine in my living room. Today it is a design and manufacturing enterprise. That gap was bridged one order at a time.</p>',
                'cover_image'  => $u.'1574365569389-a10d488ca3fb'.$q,
                'published'    => 1,
                'published_at' => '2026-05-21 16:58:42',
                'category'     => 'Corporate',
                'created_at'   => '2026-05-26 16:58:42',
                'updated_at'   => '2026-05-27 02:56:24',
            ],
            [
                'id'           => 5,
                'title'        => 'African Craftsmanship in the Modern World: Why It Matters More Than Ever',
                'slug'         => 'african-craftsmanship-in-the-modern-world',
                'excerpt'      => 'Mass production is everywhere. Ruth argues that the answer is not to compete — it is to go deeper into what makes African craft irreplaceable.',
                'body'         => '<p>We live in a world flooded with cheap, fast, disposable goods. Furniture assembled from flatpack boxes. Bags made in factories where no single person made the whole thing.</p><p>In this world, African craftsmanship is not a quaint tradition. It is a radical act.</p><h2>What Makes African Craft Different</h2><p>When a craftsperson at My Perfect Stitch builds a chair, they know that chair. They selected the wood. They cut it. They joined it. They finished it. They know its weight and its grain. That level of intimate knowledge is almost entirely absent from mass-produced goods.</p><p>And increasingly, people are noticing. They are tired of things that break. They are tired of owning nothing with a story. They are tired of spaces that feel borrowed rather than lived-in.</p><h2>The Opportunity for African Designers</h2><p>The world is ready for what we have always made. Bold forms. Natural materials. Objects that carry meaning and memory. The question is not whether there is a market — there clearly is. The question is whether we are willing to own our craft without apology.</p><p>African designers and makers need to stop underselling themselves. The hand-built side table is not worth less than the factory equivalent — it is worth more. Price accordingly. Tell the story of the hands that made it.</p>',
                'cover_image'  => $u.'1578509566163-068acd11b8e7'.$q,
                'published'    => 1,
                'published_at' => '2026-05-12 16:58:42',
                'category'     => 'Insights',
                'created_at'   => '2026-05-26 16:58:42',
                'updated_at'   => '2026-05-27 02:56:25',
            ],
            [
                'id'           => 6,
                'title'        => 'From Government Office to Workshop Floor: My Entrepreneurship Journey',
                'slug'         => 'from-government-office-to-workshop-floor',
                'excerpt'      => 'The full story of how Ruth Kayira left a stable career in the Zambian public service to build My Perfect Stitch from the ground up.',
                'body'         => '<p>Leaving a government job in Zambia to start a furniture and fashion business makes no sense on paper. But businesses are not built on paper.</p><h2>The Career I Had</h2><p>I spent eight years in the Zambian public service. It was a good career — respected, stable, with a clear path forward. But every evening and every weekend, I went home and I made things. The making was not a hobby — it was the most alive I ever felt.</p><h2>The Decision</h2><p>The decision to leave came in small moments of clarity over several years. A client who paid more for one of my bags than I made in a week at work. A corporate client who asked if I could furnish their entire boardroom. A friend who said, quietly: "Ruth, this is what you are supposed to be doing."</p><p>I saved for two years. I built a small client base on evenings and weekends. I drew up a rough business plan. And then, one morning, I handed in my resignation.</p><h2>The First Year</h2><p>The first year was hard in terms of identity. I had been a government official for almost a decade. The answer turned out to be: furniture maker, fashion designer, and entrepreneur. My Perfect Stitch became the fullest expression of who I am.</p>',
                'cover_image'  => $u.'1769578683495-88c7c5adbaad'.$q,
                'published'    => 1,
                'published_at' => '2026-04-26 16:58:42',
                'category'     => 'Lifestyle',
                'created_at'   => '2026-05-26 16:58:42',
                'updated_at'   => '2026-05-27 02:56:25',
            ],
            [
                'id'           => 7,
                'title'        => 'How My Perfect Stitch Designs Furniture That Lasts a Lifetime',
                'slug'         => 'how-my-perfect-stitch-designs-furniture-that-lasts-a-lifetime',
                'excerpt'      => 'Inside the design and production process at My Perfect Stitch — from first sketch to finished piece.',
                'body'         => '<p>Every piece of furniture that leaves the My Perfect Stitch workshop has been through a process that most factory-made items never experience: it has been thought about. Deeply, carefully, from every angle.</p><h2>It Starts With a Conversation</h2><p>Every commission begins with a conversation about the space the piece will live in, the light, and the client — how they move through a room, what they value, what story they want their home to tell. Only after that do we begin sketching.</p><h2>Materials That Mean Something</h2><p>We source timber from responsible local suppliers in Zambia — mukwa, mahogany, teak — known for durability and beauty. Our upholstery is sourced from African textile mills wherever possible: bold patterns, rich textures, chosen for daily use.</p><h2>Built to Be Fixed</h2><p>We use traditional joinery — mortise-and-tenon, dovetail, tongue-and-groove — because they produce strong, repairable bonds. A piece built this way is designed to be in your family for fifty years. That is not just good craft. That is good business for the planet.</p><h2>The Finish</h2><p>We hand-sand every surface through multiple grades and apply oil and wax finishes that protect the wood while letting its natural colour and grain come forward. The finish is the face of the piece. It deserves the time we give it.</p>',
                'cover_image'  => $u.'1774709440530-b6916d8c36df'.$q,
                'published'    => 1,
                'published_at' => '2026-04-11 16:58:42',
                'category'     => 'Insights',
                'created_at'   => '2026-05-26 16:58:43',
                'updated_at'   => '2026-05-27 02:56:25',
            ],
            [
                'id'           => 8,
                'title'        => 'Ruth Kayira Named Among Zambia\'s Top Business Voices of 2024',
                'slug'         => 'ruth-kayira-zambia-top-business-voices-2024',
                'excerpt'      => 'My Perfect Stitch founder Ruth Kayira Mooto was recognised as one of Zambia\'s most influential business voices for her work championing creative entrepreneurship.',
                'body'         => '<p>Ruth Kayira Mooto has been recognised as one of Zambia\'s top business voices for 2024 — a milestone that reflects both her entrepreneurial journey and her growing influence as a public advocate for African creative enterprise.</p><h2>The Recognition</h2><p>The annual list highlights individuals who have made a measurable impact on Zambia\'s commercial and cultural landscape. Ruth was cited for her TEDx work, her contributions to the local crafts manufacturing sector, and her role as a mentor to young entrepreneurs across the country.</p><blockquote>"Ruth represents the kind of entrepreneur Zambia needs more of. She is not just building a business — she is building an argument for what African design can be at a global level."</blockquote><h2>What Is Next for My Perfect Stitch</h2><p>Ruth is currently expanding workshop capacity to take on larger commercial interiors commissions. Plans are also underway for a new accessories collection and a formal mentorship programme for young Zambian designers — a structured pathway from craft skill to business confidence.</p>',
                'cover_image'  => $u.'1590650153855-d9e808231d41'.$q,
                'published'    => 1,
                'published_at' => '2026-03-27 16:58:42',
                'category'     => 'Corporate',
                'created_at'   => '2026-05-26 16:58:43',
                'updated_at'   => '2026-05-27 03:02:31',
            ],
        ]);

        // ── Projects ──────────────────────────────────────────────────────
        DB::table('projects')->insert([
            [
                'id'          => 1,
                'slug'        => 'custom-furniture',
                'title'       => 'Custom Furniture Collection',
                'tagline'     => 'Bespoke handcrafted furniture pieces rooted in African craftsmanship and bold functional design.',
                'client'      => 'My Perfect Stitch',
                'date_range'  => '2018 – Present',
                'services'    => 'Custom Furniture Design',
                'deliverables'=> 'Bespoke Furniture Pieces',
                'website_url' => null,
                'icon_url'    => null,
                'hero_image'  => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'image_1'     => $u.'1720247520862-7e4b14176fa8'.$q,
                'image_2'     => $u.'1774709440530-b6916d8c36df'.$q,
                'exec_image'  => $u.'1720247520862-7e4b14176fa8'.$q,
                'about_col1'  => 'The Custom Furniture Collection is at the heart of My Perfect Stitch. Each piece is designed and built to order, incorporating locally sourced materials and the hands of skilled Zambian artisans. No two pieces are exactly alike — every commission starts with a conversation about function, space, and identity.',
                'about_col2'  => 'Ruth\'s design philosophy for furniture is simple: bold, purposeful, and built to last. Influences drawn from African geometric patterns and natural textures are woven into every chair, table, and shelving unit — creating pieces that feel rooted in heritage while fitting perfectly into modern spaces.',
                'exec_col1'   => 'Each furniture commission begins with a consultation to understand the client\'s vision, space dimensions, and material preferences. From there, Ruth\'s team produces detailed design sketches and material samples before a single cut is made.',
                'exec_col2'   => 'Production takes place in-house at the My Perfect Stitch workshop, where traditional joinery techniques meet contemporary finishing. Quality control is hands-on at every stage, ensuring every piece that leaves the studio meets the highest standards of craft and durability.',
                'category'    => 'Furniture',
                'sort_order'  => 1,
                'published'   => 1,
                'created_at'  => '2026-05-26 16:49:03',
                'updated_at'  => '2026-05-26 16:49:03',
            ],
            [
                'id'          => 2,
                'slug'        => 'branded-interiors',
                'title'       => 'Branded Interiors',
                'tagline'     => 'Custom interior spaces designed for corporate and residential clients — bold, identity-driven environments rooted in African aesthetics.',
                'client'      => 'Corporate & Residential Clients',
                'date_range'  => '2019 – Present',
                'services'    => 'Interior Design & Branding',
                'deliverables'=> 'Fully Designed Spaces',
                'website_url' => null,
                'icon_url'    => null,
                'hero_image'  => $u.'1720247520862-7e4b14176fa8'.$q,
                'image_1'     => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'image_2'     => $u.'1578509566163-068acd11b8e7'.$q,
                'exec_image'  => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'about_col1'  => 'The Branded Interiors service is My Perfect Stitch\'s answer to clients who want their physical spaces to reflect who they truly are. Whether it\'s a corporate boardroom that speaks authority, or a residential living room that feels like home, Ruth brings the same creative rigour to every space.',
                'about_col2'  => 'Every interior project begins with a deep-dive into the client\'s identity — their values, their audience, and the feeling they want people to have when they walk through the door. The result is a space that tells a story without saying a word.',
                'exec_col1'   => 'The process combines a thorough brief with mood-boarding, material selection, and 2D layout planning. Ruth works closely with clients throughout, ensuring that every decision — from flooring to furniture placement — aligns with the overall design vision.',
                'exec_col2'   => 'Installation is managed end-to-end by the My Perfect Stitch team. Custom furniture pieces, curated décor, and locally sourced finishing materials are brought together on-site to create a cohesive, polished space that exceeds client expectations.',
                'category'    => 'Interiors',
                'sort_order'  => 2,
                'published'   => 1,
                'created_at'  => '2026-05-26 16:49:03',
                'updated_at'  => '2026-05-26 16:49:03',
            ],
            [
                'id'          => 3,
                'slug'        => 'fashion-bags',
                'title'       => 'Fashion & Bags',
                'tagline'     => 'High-quality bags and textile-based fashion products rooted in African heritage and contemporary style.',
                'client'      => 'My Perfect Stitch – Accessories Line',
                'date_range'  => '2020 – Present',
                'services'    => 'Fashion Design & Manufacturing',
                'deliverables'=> 'Bags, Totes & Accessories',
                'website_url' => null,
                'icon_url'    => null,
                'hero_image'  => $u.'1574365569389-a10d488ca3fb'.$q,
                'image_1'     => $u.'1578509566163-068acd11b8e7'.$q,
                'image_2'     => $u.'1769578683495-88c7c5adbaad'.$q,
                'exec_image'  => $u.'1574365569389-a10d488ca3fb'.$q,
                'about_col1'  => 'The Fashion & Bags line grew naturally out of Ruth\'s love for textiles and wearable design. Each bag in the collection is made from premium materials, selected for both quality and their ability to carry the visual language of African design — bold patterns, rich textures, and confident forms.',
                'about_col2'  => 'From structured totes to everyday crossbody bags, every piece in the collection is designed to be functional without sacrificing personality. Ruth\'s accessories are for women who want to carry something that means something — a product with a story and a soul.',
                'exec_col1'   => 'Designs begin on paper — Ruth sketches every bag herself before patterns are cut. Material sourcing prioritises local suppliers and quality leather, with each batch reviewed before production begins to ensure consistency across the line.',
                'exec_col2'   => 'The bags are produced in small batches at the My Perfect Stitch workshop, with each piece hand-finished by skilled artisans. This approach ensures quality at every stage and keeps the collection intentionally curated — never mass-produced.',
                'category'    => 'Accessories',
                'sort_order'  => 3,
                'published'   => 1,
                'created_at'  => '2026-05-26 16:49:04',
                'updated_at'  => '2026-05-26 16:49:04',
            ],
            [
                'id'          => 4,
                'slug'        => 'the-harvest-table',
                'title'       => 'The Harvest Table',
                'tagline'     => 'A ten-seat dining table handcrafted from reclaimed Zambian Mukwa hardwood.',
                'client'      => 'Private Residence, Lusaka',
                'date_range'  => '2023',
                'services'    => 'Custom Furniture, Joinery, Hand Finishing',
                'deliverables'=> 'One dining table, ten matching chairs',
                'website_url' => null,
                'icon_url'    => null,
                'hero_image'  => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'image_1'     => $u.'1774709440530-b6916d8c36df'.$q,
                'image_2'     => $u.'1720247520862-7e4b14176fa8'.$q,
                'exec_image'  => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'about_col1'  => 'The Harvest Table began as a simple brief: a family wanted a dining table large enough to seat three generations at once. What we delivered was something that will outlast all of them. Crafted entirely from reclaimed Mukwa — a dense, richly grained hardwood native to Zambia — every plank was selected for character, not uniformity.',
                'about_col2'  => 'The design draws from the broad, confident proportions of traditional Zambian communal furniture, updated with clean, contemporary lines. No veneers. No shortcuts. The table stands on hand-turned legs with mortise-and-tenon joinery that requires no metal fixings. It is furniture made to be inherited.',
                'exec_col1'   => 'The Mukwa was sourced from a demolition site and air-dried for three months before any cut was made. Each plank was hand-planed to reveal the grain beneath, then book-matched to create a surface that reads as a single continuous piece of wood despite being assembled from seven boards.',
                'exec_col2'   => 'Finishing was done entirely by hand — five coats of a linseed and beeswax blend, hand-buffed between each coat. The result is a surface that is warm to the touch and deepens with age. Delivery was a family event. The client\'s grandmother sat at the head of the table before it had been fully set down and declared it home.',
                'category'    => 'Furniture',
                'sort_order'  => 4,
                'published'   => 1,
                'created_at'  => '2026-05-28 13:17:25',
                'updated_at'  => '2026-05-28 13:17:25',
            ],
            [
                'id'          => 5,
                'slug'        => 'lusaka-creative-lounge',
                'title'       => 'Lusaka Creative Lounge',
                'tagline'     => 'A branded co-working lounge designed to feel like creative Zambia looks.',
                'client'      => 'Lusaka Tech & Creative Hub',
                'date_range'  => '2024',
                'services'    => 'Interior Design, Custom Furniture, Textile & Upholstery',
                'deliverables'=> 'Full lounge fit-out — seating, workstations, reception, soft furnishings',
                'website_url' => null,
                'icon_url'    => null,
                'hero_image'  => $u.'1578509566163-068acd11b8e7'.$q,
                'image_1'     => $u.'1720247520862-7e4b14176fa8'.$q,
                'image_2'     => $u.'1653971858474-4f2dfa7f4dc1'.$q,
                'exec_image'  => $u.'1578509566163-068acd11b8e7'.$q,
                'about_col1'  => 'The brief was to create a co-working lounge that felt unmistakably Zambian without relying on cliché. The client — a creative and technology hub in the heart of Lusaka — wanted a space that young African professionals would be proud to work from, photograph, and share. What we built was an interior that draws its language from the land: ochre walls, woven textiles, dark timber, and light that moves.',
                'about_col2'  => 'Every piece of furniture was designed and made by My Perfect Stitch in the studio. The upholstery combines locally woven chitengi fabric with full-grain leather in a palette drawn from the Zambian savanna. The result is a space that is immediately recognisable as African — not because of what is displayed, but because of what it is made from.',
                'exec_col1'   => 'The project was completed in eleven weeks from brief to handover, working around the hub\'s live operations. We built in modular sections — each zone of the lounge was delivered and installed as a complete unit — so the space was never entirely out of service during the fit-out.',
                'exec_col2'   => 'Workstations were designed to convert between individual focus work and collaborative table arrangements. The reception desk is a single piece of solid Mahogany, twelve feet wide, with a hand-stitched leather top surface. Since opening, the lounge has been featured in two regional design publications and has become one of the most photographed interiors in Lusaka.',
                'category'    => 'Interiors',
                'sort_order'  => 5,
                'published'   => 1,
                'created_at'  => '2026-05-28 13:17:34',
                'updated_at'  => '2026-05-28 13:17:34',
            ],
        ]);

        // ── Site settings ─────────────────────────────────────────────────
        DB::table('site_settings')->insert([
            ['key'=>'home_hero_title',    'value'=>"Hello, I am Ruth.\nFounder & Creative Director.", 'created_at'=>'2026-05-26 16:49:05','updated_at'=>'2026-05-28 13:44:02'],
            ['key'=>'home_hero_subtitle', 'value'=>'I blend African craftsmanship with bold, functional design — championing small beginnings into great enterprises through My Perfect Stitch.','created_at'=>'2026-05-26 16:49:06','updated_at'=>'2026-05-26 16:49:06'],
            ['key'=>'home_hero_button',   'value'=>'Contact me','created_at'=>'2026-05-26 16:49:06','updated_at'=>'2026-05-26 16:49:06'],
            ['key'=>'home_about_title',   'value'=>'About Ruth','created_at'=>'2026-05-26 16:49:06','updated_at'=>'2026-05-26 16:49:06'],
            ['key'=>'home_about_body',    'value'=>"<p>Ruth Kayira Mooto is a Zambian entrepreneur, public speaker, and founder of My Perfect Stitch. She made a bold leap from a stable career as a government official to build a thriving creative enterprise rooted in African craftsmanship.</p>\r\n<p>Her work champions the belief that a hobby can be the start of a million-dollar business. Through My Perfect Stitch, she designs custom furniture, branded interiors, and fashion accessories that fuse bold aesthetics with functional purpose.</p>",'created_at'=>'2026-05-26 16:49:06','updated_at'=>'2026-05-28 13:43:33'],
            ['key'=>'home_about_link_text','value'=>'More about Ruth','created_at'=>'2026-05-26 16:49:07','updated_at'=>'2026-05-26 16:49:07'],
            ['key'=>'about_hero_title',   'value'=>'About Ruth','created_at'=>'2026-05-26 16:49:07','updated_at'=>'2026-05-26 16:49:07'],
            ['key'=>'about_hero_subtitle','value'=>'Zambian entrepreneur, public speaker, and founder of My Perfect Stitch — transforming African craftsmanship into bold, functional design and inspiring a generation of purpose-driven entrepreneurs.','created_at'=>'2026-05-26 16:49:07','updated_at'=>'2026-05-26 16:49:07'],
            ['key'=>'about_story_title',  'value'=>'My Story','created_at'=>'2026-05-26 16:49:07','updated_at'=>'2026-05-26 16:49:07'],
            ['key'=>'about_story_body',   'value'=>"<p>Ruth Kayira Mooto began her career in the Zambian public service, building a stable and respected professional life. But beneath the surface, a creative passion was quietly growing — one that would change the course of her life entirely.</p>\r\n<p>She founded My Perfect Stitch as a way to channel her love for design and craftsmanship. What started as a hobby evolved into a full-scale design and manufacturing enterprise producing custom furniture, branded interiors, and fashion accessories rooted in African heritage.</p>\r\n<p>Today, Ruth is one of Zambia's boldest entrepreneurial voices. Her TEDx talk, \"What If Your Hobby Is the Start of a Million-Dollar Business?\", has inspired thousands to champion their own small beginnings.</p>",'created_at'=>'2026-05-26 16:49:07','updated_at'=>'2026-05-28 13:43:33'],
            ['key'=>'highlight_1_role',   'value'=>'Founder & Creative Director','created_at'=>'2026-05-28 13:43:34','updated_at'=>'2026-05-28 13:45:42'],
            ['key'=>'highlight_1_org',    'value'=>'My Perfect Stitch','created_at'=>'2026-05-28 13:43:34','updated_at'=>'2026-05-28 13:45:43'],
            ['key'=>'highlight_1_from',   'value'=>'2018','created_at'=>'2026-05-28 13:43:34','updated_at'=>'2026-05-28 13:45:43'],
            ['key'=>'highlight_1_to',     'value'=>'Present','created_at'=>'2026-05-28 13:43:35','updated_at'=>'2026-05-28 13:45:43'],
            ['key'=>'highlight_2_role',   'value'=>'TEDx Speaker','created_at'=>'2026-05-28 13:43:35','updated_at'=>'2026-05-28 13:45:44'],
            ['key'=>'highlight_2_org',    'value'=>'"What If Your Hobby Is the Start of a Million-Dollar Business?"','created_at'=>'2026-05-28 13:43:36','updated_at'=>'2026-05-28 13:45:44'],
            ['key'=>'highlight_2_from',   'value'=>'2022','created_at'=>'2026-05-28 13:43:36','updated_at'=>'2026-05-28 13:45:44'],
            ['key'=>'highlight_2_to',     'value'=>'Present','created_at'=>'2026-05-28 13:43:37','updated_at'=>'2026-05-28 13:45:44'],
            ['key'=>'highlight_3_role',   'value'=>'Government Official','created_at'=>'2026-05-28 13:43:37','updated_at'=>'2026-05-28 13:45:45'],
            ['key'=>'highlight_3_org',    'value'=>'Zambian Public Service','created_at'=>'2026-05-28 13:43:37','updated_at'=>'2026-05-28 13:45:45'],
            ['key'=>'highlight_3_from',   'value'=>'2010','created_at'=>'2026-05-28 13:43:38','updated_at'=>'2026-05-28 13:45:46'],
            ['key'=>'highlight_3_to',     'value'=>'2018','created_at'=>'2026-05-28 13:43:38','updated_at'=>'2026-05-28 13:45:46'],
        ]);

        // ── Pages (update content JSON) ───────────────────────────────────
        DB::table('pages')->where('slug', 'about')->update([
            'content'    => json_encode([
                'hero_title'         => 'About Ruth',
                'hero_subtitle'      => 'Zambian entrepreneur, public speaker, and founder of My Perfect Stitch — transforming African craftsmanship into bold, functional design and inspiring a generation of purpose-driven entrepreneurs.',
                'story_body'         => "<p>Ruth Kayira Mooto began her career in the Zambian public service, building a stable and respected professional life. But beneath the surface, a creative passion was quietly growing — one that would change the course of her life entirely.</p>\n<p>She founded My Perfect Stitch as a way to channel her love for design and craftsmanship. What started as a hobby evolved into a full-scale design and manufacturing enterprise producing custom furniture, branded interiors, and fashion accessories rooted in African heritage.</p>\n<p>Today, Ruth is one of Zambia's boldest entrepreneurial voices. Her TEDx talk, \"What If Your Hobby Is the Start of a Million-Dollar Business?\", has inspired thousands to champion their own small beginnings.</p>",
                'recognition_1_role' => 'Fashion & Accessories',
                'recognition_1_org'  => 'TEDx Talk, 2022',
                'recognition_1_from' => '2022',
                'recognition_1_to'   => 'Present',
                'recognition_2_role' => 'Entrepreneur Award',
                'recognition_2_org'  => 'Zambia Creative Industries',
                'recognition_2_from' => '2021',
                'recognition_2_to'   => 'Present',
                'recognition_3_role' => 'Business Studies',
                'recognition_3_org'  => 'University of Zambia',
                'recognition_3_from' => '2005',
                'recognition_3_to'   => '2009',
                'journey_intro'      => 'From public service to creative entrepreneurship — a path built on courage, creativity, and community.',
                'journey_1_org'      => 'My Perfect Stitch',
                'journey_1_title'    => 'Founder & Creative Director',
                'journey_1_from'     => '2018',
                'journey_1_to'       => 'Present',
                'journey_1_desc'     => 'Founded and scaled My Perfect Stitch into a design and manufacturing enterprise producing custom furniture, branded interiors, and fashion accessories rooted in African craftsmanship.',
                'journey_2_org'      => 'Zambian Public Service',
                'journey_2_title'    => 'Government Official',
                'journey_2_from'     => '2010',
                'journey_2_to'       => '2018',
                'journey_2_desc'     => 'Served in the Zambian public service, developing leadership and administrative skills before transitioning to full-time entrepreneurship. This foundation shaped her disciplined approach to business.',
                'journey_3_org'      => 'TEDx & Public Speaking',
                'journey_3_title'    => 'Speaker & Mentor',
                'journey_3_from'     => '2015',
                'journey_3_to'       => 'Present',
                'journey_3_desc'     => 'Delivered a TEDx talk on entrepreneurship and purpose-driven business. Mentors young African entrepreneurs, advocating for creativity, community, and the courage to start small.',
                'service_1_title'    => 'Branded Interiors',
                'service_1_desc'     => 'Designing custom spaces for corporate and residential clients — bold, identity-driven environments rooted in African aesthetics.',
                'service_2_title'    => 'Custom Furniture',
                'service_2_desc'     => 'Bespoke, high-quality furniture pieces incorporating local craftsmanship and modern design.',
                'service_3_title'    => 'Fashion & Accessories',
                'service_3_desc'     => 'High-quality bags and textile-based products rooted in African heritage and contemporary style.',
                'service_4_title'    => 'Manufacturing & Scale',
                'service_4_desc'     => 'Operating as a design and manufacturing hub — moving beyond handmade to a scalable enterprise model.',
            ]),
            'updated_at' => now(),
        ]);

        DB::table('pages')->where('slug', 'contact')->update([
            'content'    => json_encode([
                'hero_title'     => 'Get In Touch',
                'hero_subtitle'  => 'Interested in a custom order, a collaboration, or booking Ruth for a speaking engagement? Reach out below.',
                'social_facebook'  => 'https://www.facebook.com/',
                'social_twitter'   => 'https://twitter.com/',
                'social_linkedin'  => 'https://www.linkedin.com/',
                'social_instagram' => 'https://www.instagram.com/',
                'social_tiktok'    => 'https://www.tiktok.com/',
                'social_whatsapp'  => 'https://www.whatsapp.com/',
                'faq_1_question' => 'What drives you as a person?',
                'faq_1_answer'   => 'A deep belief that African craftsmanship and creativity deserve to stand at the front of the global stage — not the sidelines. I am driven by the desire to build things that last, to mentor the next generation of makers, and to prove that purpose and ambition can exist in the same sentence.',
                'faq_2_question' => 'What does a typical day look like for you?',
                'faq_2_answer'   => 'There is no such thing as a typical day, and I have learned to be grateful for that. Most mornings start early and quietly — I think best before the noise begins. The rest of the day moves between the studio floor, client conversations, writing, and the occasional meeting I could have been an email. I try to end each day with something made, even if it is just a decision.',
                'faq_3_question' => 'What is one thing most people do not know about you?',
                'faq_3_answer'   => 'That I spent years working in government before any of this. I was not always an entrepreneur — I was someone with a quiet idea and a full-time job that had nothing to do with design. The leap was not dramatic. It was slow, deliberate, and sometimes terrifying. That backstory shapes how I think about risk and patience.',
                'faq_4_question' => 'How do you stay grounded when things get hard?',
                'faq_4_answer'   => 'I make something with my hands. It sounds simple, but there is something about the act of making — measuring, cutting, assembling — that resets everything for me. When my head is full of noise, my hands know what to do. That has never failed me.',
            ]),
            'updated_at' => now(),
        ]);
    }
}
